spring:
  application:
    name: chatbot
auth:
    openai:
      api-key: ${OPENAI_API_KEY}
    app:
      api-key: ${AUTH_API_KEY}
openai:
  model: gpt-3.5-turbo
  url: https://api.openai.com/v1/chat/completions
  context: ${AI_CONTEXT}